import type { Metadata } from 'next'
import { Roboto_Slab, Roboto } from 'next/font/google'
import './globals.css'
import NavBar from './navbar'

const robotoSlab = Roboto_Slab({ subsets: ['latin'], variable: "--font-roboto-slab" })
const roboto = Roboto({ subsets: ['latin'], style: ["normal", "italic"], weight: ["300", "400"], variable: "--font-roboto" })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${robotoSlab.variable} ${roboto.variable}`}>
        <NavBar />
        {children}
      </body>
    </html>
  )
}
